### ISSUE TITLE
Covariance balance test fails with categorical data

### ISSUE THREAD

**Issue by Naeemkh** [fasrc/GPSmatching#23]
The following line in AbsoluteCorrFun requires numeric values. Covariates should be numeric values. 

abs(cor(w,c[[i]],method = c("spearman")))

**Comment by wxwx1993** [comment]
spearman correlation may only apply to continuous variables.

**Comment by Naeemkh** [comment]
@wxwx1993 Then we need to drop categorical variables in spearman correlation test (inside  R/covariate_balance.R), correct?

**Comment by m-qin** [comment]
Hello! I'm using CausalGPS and finding that my categorical variables, which are passed into `generate_pseudo_pop()` as factors, are showing up in the covariate balance plot and covariate balance objects as having an absolute correlation with the exposure. Does anyone know why this is or what this means?

To assess balance on a categorical variable, I suppose I should instead examine the distribution of the (continuous) exposure within each category and perhaps perform a t-test or print the standardized mean difference between each pair of categories.

**Comment by daniellebraun** [comment]
@wxwx1993

**Comment by Naeemkh** [comment]
Hi @m-qin, most of the examples in the package have at least one variable as a factor. Please see the example on this page:

https://fasrc.github.io/CausalGPS/articles/CausalGPS.html

I do not think the factor is the problem. There might be another problem that is worth investigating and addressing it. 
BTW, we are using `polycor::polyserial` function to compute correlation in factor variables. 

Please see more here: 
https://github.com/fasrc/CausalGPS/blob/master/R/absolute_corr_fun.R

**Comment by m-qin** [comment]
Thanks for these links @Naeemkh! They are really helpful.

The `polycor::polyserial` documentation says it "computes the polyserial correlation... between a quantitative variable and an **ordinal** variable, based on the assumption that the joint distribution of the quantitative variable and a latent continuous variable underlying the ordinal variable is **bivariate normal**."

So I think I will continuing using this function for **ordinal** categorical covariates, but I will remove my **unordered** categorical covariates (such as `region`, which is in the CausalGPS's examples) from the function and from the mean absolute correlation (covariate balance) plots.

For these unordered categorical covariates, I think I can either make a boxplot of the exposure in each category of the covariate, or I can plot/record the standardized mean difference between the exposure in each category.

**Comment by daniellebraun** [comment]
tagging @wxwx1993

**Comment by wxwx1993** [comment]
Sounds good! Or you can try some/every combination of "orders" for the unordered categorical variables. If all polyserial correlations returned ~0, it also indicated evidence of covariate balance.

**Comment by m-qin** [comment]
Hi @wxwx1993! @danielmork had a great idea for unordered categorical covariates, which I'm now using in my code: 1) creating binary indicator variables for each level of the categorical covariate, 2) calculating the [point-biserial correlation](https://en.wikipedia.org/wiki/Point-biserial_correlation_coefficient) between that binary indicator and the exposure, then 3) taking the absolute value of #2, and 4) taking the mean of #3 for all binary indicators of that covariate.
