### ISSUE TITLE
generate_synthetic_data parameter description

### ISSUE THREAD

**Issue by Naeemkh** [fasrc/GPSmatching#6]
Please add parameters description to the generate_synthetic_data function. 

```
#' @param sample_size sample size description
#' @param seed seed description
#' @param outcome_sd outcpme_sd description
#' @param gps_spec gps_spec description
#' @param cova_spec cova_spec description
```

**Comment by daniellebraun** [comment]
hi @Naeemkh is @wxwx1993's data generating function for simulations somewhere in the repo? if you can point me to it I can try to add a description. thanks

**Comment by Naeemkh** [comment]
@daniellebraun , please select `develop` branch. Here is the link:

https://github.com/fasrc/GPSmatching/tree/develop

**Comment by daniellebraun** [comment]
thanks @Naeemkh, can you let us know specifically which parameters you have questions on? 
sample size of cohort, seed for generating all synthetic data, sd for generating outcome (would be helpful to add other info about outcome, what model is used to generate it to documentation), gps_spec (choice of a few models to generate gps need to list out choices), cova_spec (choice of a few models to generate covariates, need to list out choices)

**Comment by Naeemkh** [comment]
@daniellebraun please provide description for the following three:

#' @param outcome_sd outcpme_sd description
#' @param gps_spec gps_spec description
#' @param cova_spec cova_spec description
